name: ACL4SSR_Online_Full_AdblockPlus Convert, Update Gist

on:
  # 当有代码推送到 main 分支时触发
  push:
    branches:
      - main
  
  # 手动触发
  workflow_dispatch:

  # 定时触发器
  schedule:
    # CRON 表达式使用 UTC 时间。
    # 这个表达式表示在每周一的 08:00 (UTC) 触发。
    - cron: '0 8 * * 1'



jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'

      - name: Build project
        run: make build
      
      - name: Generate content
        id: generate_content
        run: |
          {
            echo 'gist_content<<EOF'
            ./acl-convert https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/config/ACL4SSR_Online_Full_AdblockPlus.ini
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Update Gist
        env:
          # 从 Secrets 中读取 PAT 和 Gist ID，并设置为环境变量
          GH_TOKEN: ${{ secrets.GIST_PAT }}
          GIST_ID: ${{ secrets.GIST_ID }}
          YAML_CONTENT: ${{ steps.generate_content.outputs.gist_content }}
        run: |
          json_payload=$(jq -n \
            --arg content "$YAML_CONTENT" \
            '{
              "description": "ACL yaml config",
              "files": {
                "ACL4SSR_Online_Full_AdblockPlus.yaml": {
                  "content": $content
                }
              }
            }')

          # 现在，将这个格式完美的 JSON payload 发送给 API
          # 注意 -d 后面现在是一个包含了转义后内容的变量
          curl -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Content-Type: application/json" \
            https://api.github.com/gists/$GIST_ID \
            -d "$json_payload"
